version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:latest
   steps:
      - run:
          name: proses anu
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd curl
           curl https://raw.githubusercontent.com/RooGhz720/RooGhz720/main/builder.sh > builder.sh
           chmod +x builder.sh
           bash builder.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile

